### ISSUE TITLE
ETS problem with Clock as application in umbrella project

### ISSUE THREAD

**Issue by pcarvsilva** [danielberkompas/cloak#111]
:ets.lookup(MyApp.Vault.Config, :config)  
* 1st argument: the table identifier does not refer to an existing ETS table

**Comment by acrolink** [comment]
I am facing the same issue, what is the solution?

**Comment by MeerKatDev** [comment]
still no solution?

**Comment by gmile** [comment]
Same issue.

@pcarvsilva would you happen to be able to share the solution you've arrived at at the end? 🤞

**Comment by pcarvsilva** [comment]
@gmile I've migrrated to Oban

**Comment by gmile** [comment]
We found what was causing this issue for us. In our case, this was happening in tests, and was caused by a combination of factors, which may not be relevant here. However, the important clue that helped us untangle this: missing `MyApp.Vault.Config` meant vault process was dead or haven't started.

After looking closer, we identified that many other processes that typically must be alive - are not alive. Which lead us to a discovery related to mocking in tests: mocking some code was causing app tree to completely die.

I wrote about it a bit here: https://elixirforum.com/t/an-issue-with-mock-library/51514/5?u=gmile
